import { Note, NoteColorConfig, NoteColorId } from '@/types/note';

export const NOTE_COLORS: Record<NoteColorId, NoteColorConfig> = {
  default: {
    id: 'default',
    name: 'Luna Navy (Default)',
    bgLight: 'bg-white',
    bgDark: 'dark:bg-[#023859]',
    borderLight: 'border-[#A7EBF2]/80',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#023859',
  },
  fog: {
    id: 'fog',
    name: 'Ice Blue',
    bgLight: 'bg-[#F0FBFC]',
    bgDark: 'dark:bg-[#023859]/90',
    borderLight: 'border-[#A7EBF2]',
    borderDark: 'dark:border-[#54ACBF]/70',
    dotColor: '#A7EBF2',
  },
  sage: {
    id: 'sage',
    name: 'Ocean Aqua',
    bgLight: 'bg-[#EAF6F8]',
    bgDark: 'dark:bg-[#04436A]',
    borderLight: 'border-[#54ACBF]/70',
    borderDark: 'dark:border-[#54ACBF]',
    dotColor: '#54ACBF',
  },
  storm: {
    id: 'storm',
    name: 'Slate Blue',
    bgLight: 'bg-[#EEF4F8]',
    bgDark: 'dark:bg-[#032A45]',
    borderLight: 'border-[#26658C]/60',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#26658C',
  },
  dusk: {
    id: 'dusk',
    name: 'Cosmic Navy',
    bgLight: 'bg-[#E7EEF5]',
    bgDark: 'dark:bg-[#011C40]',
    borderLight: 'border-[#023859]/40',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#011C40',
  },
  mint: {
    id: 'mint',
    name: 'Seafoam Aqua',
    bgLight: 'bg-[#EFFDFB]',
    bgDark: 'dark:bg-[#033E4D]',
    borderLight: 'border-[#54ACBF]/60',
    borderDark: 'dark:border-[#54ACBF]/60',
    dotColor: '#38bdf8',
  },
  sand: {
    id: 'sand',
    name: 'Starlight Gold',
    bgLight: 'bg-[#FFFBEB]',
    bgDark: 'dark:bg-[#1E3A4C]',
    borderLight: 'border-[#FDE68A]',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#fbbf24',
  },
  coral: {
    id: 'coral',
    name: 'Nebula Coral',
    bgLight: 'bg-[#FFF1F2]',
    bgDark: 'dark:bg-[#2A2B47]',
    borderLight: 'border-[#FECDD3]',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#f87171',
  },
  peach: {
    id: 'peach',
    name: 'Aurora Peach',
    bgLight: 'bg-[#FFF7ED]',
    bgDark: 'dark:bg-[#2C344E]',
    borderLight: 'border-[#FED7AA]',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#fb923c',
  },
  blossom: {
    id: 'blossom',
    name: 'Starlight Orchid',
    bgLight: 'bg-[#FAF5FF]',
    bgDark: 'dark:bg-[#1C2C4E]',
    borderLight: 'border-[#E9D5FF]',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#c084fc',
  },
  clay: {
    id: 'clay',
    name: 'Lunar Slate',
    bgLight: 'bg-[#F8FAFC]',
    bgDark: 'dark:bg-[#0A2542]',
    borderLight: 'border-[#CBD5E1]',
    borderDark: 'dark:border-[#26658C]',
    dotColor: '#64748b',
  },
};

export const INITIAL_NOTES: Note[] = [
  {
    id: 'seed-1',
    title: '✨ Welcome to My Keeps (Luna Edition)',
    content:
      'Immerse in the Luna deep-blue aesthetic:\n• Base: Deep Cosmic Navy (#011C40)\n• Surfaces: Rich Navy (#023859)\n• Accents: Ocean Aqua (#54ACBF)\n• Tags: Soft Ice Blue (#A7EBF2)\n• Borders: Slate Blue (#26658C)',
    color: 'default',
    isPinned: true,
    isArchived: false,
    isTrashed: false,
    labels: ['Luna', 'Palette'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-2',
    title: '🌙 Project Milestones',
    content:
      '• Full-Stack Next.js 16 + TypeScript architecture\n• Better Auth integrated with MongoDB Atlas\n• Light/Dark adaptive color balance with signature Navy buttons\n• Interactive Pinned vs Others notes grid',
    color: 'fog',
    isPinned: true,
    isArchived: false,
    isTrashed: false,
    labels: ['Architecture', 'Milestones'],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'seed-3',
    title: 'Deep Ocean Design Checklist',
    content: 'Ensure all components align with the Luna color rules:',
    color: 'sage',
    isPinned: false,
    isArchived: false,
    isTrashed: false,
    labels: ['Design', 'UI'],
    checklist: [
      { id: 'c1', text: 'Card background: Rich Navy (#023859)', completed: true },
      { id: 'c2', text: 'Buttons: Deep Aqua Blue (#023859 hover #26658C)', completed: true },
      { id: 'c3', text: 'Tags: Soft Ice Blue (#A7EBF2 with dark text)', completed: true },
      { id: 'c4', text: 'Card borders: Slate Blue (#26658C)', completed: true },
    ],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'seed-4',
    title: 'Thought Collection',
    content:
      'Minimalist, distraction-free writing experience. Click any note to edit or use the Luna palette to color code your thoughts.',
    color: 'storm',
    isPinned: false,
    isArchived: false,
    isTrashed: false,
    labels: ['Ideas'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'seed-5',
    title: 'Archived Meeting Notes',
    content: 'Review notes from previous sprint. Preserved cleanly in your Luna archive space.',
    color: 'dusk',
    isPinned: false,
    isArchived: true,
    isTrashed: false,
    labels: ['Archive'],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];
