import { Note, NoteColorConfig, NoteColorId } from '@/types/note';

export const NOTE_COLORS: Record<NoteColorId, NoteColorConfig> = {
  default: {
    id: 'default',
    name: 'Default',
    bgLight: 'bg-white',
    bgDark: 'dark:bg-neutral-900',
    borderLight: 'border-neutral-200/80',
    borderDark: 'dark:border-neutral-800',
    dotColor: '#e5e7eb',
  },
  coral: {
    id: 'coral',
    name: 'Coral',
    bgLight: 'bg-rose-50',
    bgDark: 'dark:bg-rose-950/40',
    borderLight: 'border-rose-200',
    borderDark: 'dark:border-rose-800/60',
    dotColor: '#fca5a5',
  },
  peach: {
    id: 'peach',
    name: 'Peach',
    bgLight: 'bg-orange-50',
    bgDark: 'dark:bg-orange-950/40',
    borderLight: 'border-orange-200',
    borderDark: 'dark:border-orange-800/60',
    dotColor: '#fdba74',
  },
  sand: {
    id: 'sand',
    name: 'Sand',
    bgLight: 'bg-amber-50',
    bgDark: 'dark:bg-amber-950/40',
    borderLight: 'border-amber-200',
    borderDark: 'dark:border-amber-800/60',
    dotColor: '#fcd34d',
  },
  mint: {
    id: 'mint',
    name: 'Mint',
    bgLight: 'bg-emerald-50',
    bgDark: 'dark:bg-emerald-950/40',
    borderLight: 'border-emerald-200',
    borderDark: 'dark:border-emerald-800/60',
    dotColor: '#6ee7b7',
  },
  sage: {
    id: 'sage',
    name: 'Sage',
    bgLight: 'bg-teal-50',
    bgDark: 'dark:bg-teal-950/40',
    borderLight: 'border-teal-200',
    borderDark: 'dark:border-teal-800/60',
    dotColor: '#5eead4',
  },
  fog: {
    id: 'fog',
    name: 'Fog',
    bgLight: 'bg-sky-50',
    bgDark: 'dark:bg-sky-950/40',
    borderLight: 'border-sky-200',
    borderDark: 'dark:border-sky-800/60',
    dotColor: '#7dd3fc',
  },
  storm: {
    id: 'storm',
    name: 'Storm',
    bgLight: 'bg-indigo-50',
    bgDark: 'dark:bg-indigo-950/40',
    borderLight: 'border-indigo-200',
    borderDark: 'dark:border-indigo-800/60',
    dotColor: '#a5b4fc',
  },
  dusk: {
    id: 'dusk',
    name: 'Dusk',
    bgLight: 'bg-purple-50',
    bgDark: 'dark:bg-purple-950/40',
    borderLight: 'border-purple-200',
    borderDark: 'dark:border-purple-800/60',
    dotColor: '#d8b4fe',
  },
  blossom: {
    id: 'blossom',
    name: 'Blossom',
    bgLight: 'bg-pink-50',
    bgDark: 'dark:bg-pink-950/40',
    borderLight: 'border-pink-200',
    borderDark: 'dark:border-pink-800/60',
    dotColor: '#f472b6',
  },
  clay: {
    id: 'clay',
    name: 'Clay',
    bgLight: 'bg-stone-100',
    bgDark: 'dark:bg-stone-900/60',
    borderLight: 'border-stone-300',
    borderDark: 'dark:border-stone-700/60',
    dotColor: '#d6d3d1',
  },
};

export const INITIAL_NOTES: Note[] = [
  {
    id: 'seed-1',
    title: '✨ Welcome to My Keeps!',
    content:
      'My Keeps is your clean, minimal workspace for thoughts, tasks, and ideas. Inspired by Google Keep with modern styling, fluid dark mode, and quick color themes.',
    color: 'sand',
    isPinned: true,
    isArchived: false,
    isTrashed: false,
    labels: ['Welcome', 'Guide'],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'seed-2',
    title: '🚀 Full-Stack Roadmap',
    content:
      'Everything is structured cleanly in Next.js:\n• Modular UI/UX with Lucide React\n• Mongoose schemas & MongoDB singleton ready\n• Next.js API Routes for CRUD operations\n• Theme switcher with localStorage persistence',
    color: 'mint',
    isPinned: true,
    isArchived: false,
    isTrashed: false,
    labels: ['Architecture', 'Tech'],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'seed-3',
    title: 'Weekend Grocery Checklist',
    content: 'Need to pick up fresh ingredients for dinner:',
    color: 'peach',
    isPinned: false,
    isArchived: false,
    isTrashed: false,
    labels: ['Personal'],
    checklist: [
      { id: 'c1', text: 'Avocados & Limes', completed: true },
      { id: 'c2', text: 'Sourdough bread', completed: true },
      { id: 'c3', text: 'Almond milk & Greek yogurt', completed: false },
      { id: 'c4', text: 'Dark roast coffee beans', completed: false },
    ],
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'seed-4',
    title: 'Product Design Ideas',
    content:
      'Consider adding voice notes, image attachments, and collaborative board sharing once backend authentication is plugged in.',
    color: 'fog',
    isPinned: false,
    isArchived: false,
    isTrashed: false,
    labels: ['Ideas', 'Design'],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'seed-5',
    title: 'Archived Meeting Notes',
    content: 'Sprint planning summary from last cycle. Kept for reference.',
    color: 'default',
    isPinned: false,
    isArchived: true,
    isTrashed: false,
    labels: ['Work'],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];
